package de.aittr.g_37_jp_shop.repository;

import de.aittr.g_37_jp_shop.domain.entity.Product;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

public interface ProductRepository extends JpaRepository<Product, Long> {
    /*
    //in this case, method body and SQL query will be generated by the framework
    Product findByTitle(String title);
     */

    //in this case, method body and SQL query will be generated by the framework, but it'll use SQL query, that we gave
    //@Query(value = "SELECT * FROM product WHERE title = :title", nativeQuery = true)
    Product findByTitle(String title);
}
